### ISSUE TITLE
Segmentation fault when ran $ ./hamr_cmd rnapileup2mismatchbed TTest.rnapileup 

### ISSUE THREAD

**Issue by Huanle** [pryvkin/hamr#2]
Hi There,

hamr_cmd failed to run due to segmentation fault.
Command used:
./hamr_cmd rnapileup2mismatchbed TTest.rnapileup

Error message:
Segmentation fault

Platform:
Linux dice02.local 2.6.32-642.3.1.el6.x86_64 #1 SMP Tue Jul 12 18:30:56 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

It works well with the test data. 
Hope you can help me fix the problem.
Thanks a lot in advance.

Huanlee

**Comment by pryvkin** [comment]
Hello,

I recommend trying https://github.com/GregoryLab/HAMR  as this fork is no longer maintained.
